name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://tboreux.hashnode.dev/rss.xml"
          date_format: dd/mm/yyyy
          template: '$newline<a href="$url">($date) “$title”</a> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="1em" style="vertical-align:middle;display:inline-block;"><title>Hashnode</title><path fill="#2962FF" d="M22.351 8.019l-6.37-6.37a5.63 5.63 0 0 0-7.962 0l-6.37 6.37a5.63 5.63 0 0 0 0 7.962l6.37 6.37a5.63 5.63 0 0 0 7.962 0l6.37-6.37a5.63 5.63 0 0 0 0-7.962zM12 15.953a3.953 3.953 0 1 1 0-7.906 3.953 3.953 0 0 1 0 7.906z"/></svg>$newline'